version: '3'
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile-auth
    ports:
      - "5001:5001"
    volumes:
      - ./data/users.db:/app/users.db
  books_service:
    build:
      context: .
      dockerfile: Dockerfile-books
    ports:
      - "5002:5002"
    volumes:
      - ./data/books.db:/app/books.db
